FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY packages/ ./packages/
COPY apps/dashboard/ ./apps/dashboard/

RUN npm install
RUN npm --workspace=@turnal/shared run build
RUN npm --workspace=@turnal/dashboard run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "--workspace=@turnal/dashboard", "run", "start"]
